- README.rst
- docs/source/conf.py
* Transfers repository and primary author to the Invenio Software
Collaboration.
> global: repository and primary author transfer

- {{ cookiecutter.project_shortname }}/requirements.py
* Makes requirements.py PEP8 compliant. (closes #5)
> global: PEP8 for requirements.py

- .editorconfig
- README.rst
- {{ cookiecutter.project_shortname }}/.editorconfig
* Adds editorconfig for both the root project and the generated project.
> global: editorconfig

- .gitignore
- .travis.yml
- README.rst
- {{ cookiecutter.project_shortname }}/.travis.yml
- {{ cookiecutter.project_shortname }}/setup.py
* Implements basic test workflow for travis.
* Adds `.gitignore` also to root folder.
> global: travis

- .editorconfig
- {{ cookiecutter.project_shortname }}/.editorconfig
* Syncs editorconfig with the changes we have made in Invenio.
> global: editorconfig sync

- {{ cookiecutter.project_shortname }}/setup.py
> installation: project_shortname as package name

- cookiecutter.json
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
> global: default values update

- .kwalitee.yml
- AUTHORS.rst
- {{ cookiecutter.project_shortname }}/CHANGES.rst
- d66b6e14df484fed65742d7abd6f5e95b004d481 docs: complete contributor list
- 91951f0c038710fae7169ee87e965131b8dfb44b docs: past tense in CHANGES.rst
- e63280546b7cf7624720b84fcb5e4f16f3449251 tests: kwalitee component names
> released-tense-kwalitee-authors

- {{ cookiecutter.project_shortname }}/setup.cfg
> babel: copyright holder and bugs address

- {{ cookiecutter.project_shortname }}/setup.cfg
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> global: fix wheel setup configuration

- {{ cookiecutter.project_shortname }}/MANIFEST.in
* Adds compiled translations files into Python package so that they
can be distributed on PyPI.
> manifest: translation files inclusion

- {{ cookiecutter.project_shortname }}/examples/app.py
* Changes from using the script as CLI to using the Flask CLI.
> examples: flask cli usage

- {{ cookiecutter.project_shortname }}/.gitignore
Signed-off-by: Bruno Cuc <bruno.cuc@cern.ch>
> global: addition of .idea/ folder to .gitignore

- {{ cookiecutter.project_shortname }}/docs/usage.rst
> global: fix usage heading

- {{ cookiecutter.project_shortname }}/run-tests.sh
* Adds bash shebang to run-tests.sh for compatibility with other
shells.
> tests: bash shebang to run-tests.sh

- {{ cookiecutter.project_shortname }}/docs/conf.py
- {{ cookiecutter.project_shortname }}/setup.py
* Fixes issue with newly released Sphinx 1.4.
> docs: sphinx 1.4 support

- .travis.yml
- {{ cookiecutter.project_shortname }}/docs/conf.py
- {{ cookiecutter.project_shortname }}/setup.py
Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>
> travis: fix sphinx nonlocal image warning

- .kwalitee.yml
- AUTHORS.rst
- cookiecutter.json
- {{ cookiecutter.project_shortname }}/RELEASE-NOTES.rst
- dea16d718375d6c790ecff95e28fe16a7dffbab2 docs: complete AUTHORS list
- e37a8fae9c975a639bd2d1e05eece9714395d98f global: inveniosoftware.org
> inveniosoftware.org

- cookiecutter.json
- {{ cookiecutter.project_shortname }}/MANIFEST.in
- {{ cookiecutter.project_shortname }}/run-tests.sh
* Default year bump and minor fixes.
> global: minor fixes

- {{ cookiecutter.project_shortname }}/.gitignore
Signed-off-by: David Caro <david@dcaro.es>
> global: ignore vim swapfiles

- {{ cookiecutter.project_shortname }}/.tx/config
> cookiecutter: .tx config slug

- docs/conf.py
- {{ cookiecutter.project_shortname }}/docs/conf.py
- {{ cookiecutter.project_shortname }}/setup.cfg
> docs: autodoc configuration and HTTP replacement

- {{ cookiecutter.project_shortname }}/.tx/config
> i18n: tx canonical slug

- README.rst
- docs/requirements.txt
> docs: move to readthedocs.io

- {{ cookiecutter.project_shortname }}/README.rst
- {{ cookiecutter.project_shortname }}/RELEASE-NOTES.rst
> cookiecutter: pythonhosted.org -> readthedocs.io

- {{ cookiecutter.project_shortname }}/run-tests.sh
> tests: isort glob fix

- {{ cookiecutter.project_shortname }}/docs/conf.py
- {{ cookiecutter.project_shortname }}/run-tests.sh
- {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/version.py
> global: test and editorconfig changes

- scripts/repocheck.py
- {{ cookiecutter.project_shortname }}/tests/conftest.py
- {{ cookiecutter.project_shortname }}/tests/test_{{cookiecutter.package_name}}.py
> [feature-betareview] tests: conftest example improvement + repo check script

- scripts/repocheck.py
- {{ cookiecutter.project_shortname }}/INSTALL.rst
- {{ cookiecutter.project_shortname }}/README.rst
- {{ cookiecutter.project_shortname }}/docs/conf.py
- {{ cookiecutter.project_shortname }}/docs/examplesapp.rst
- {{ cookiecutter.project_shortname }}/docs/index.rst
- {{ cookiecutter.project_shortname }}/examples/app.py
* Adapts README.rst to require a feature description of module and to
not show project description twice on PyPI.
* Removes bullet on free software as license is already displayed in a
badge.
> [feature-betareview] docs: README update

- scripts/repocheck.py
> [feature-betareview] global: fixed the files diff script

- {{ cookiecutter.project_shortname }}/.travis.yml
Signed-off-by: Rémi Ducceschi <remi.ducceschi@gmail.com>
> cookiecutter: add parameter "-e all" for the travis requirements

- {{ cookiecutter.project_shortname }}/.travis.yml
Is "inveniosoftware" the actual pypi username?
> global: Travis deployment section

- {{ cookiecutter.project_shortname }}/setup.py
> docs: sphinx version fix

- {{ cookiecutter.project_shortname }}/pytest.ini
- {{ cookiecutter.project_shortname }}/run-tests.sh
* Fixes issues that prevented running individual tests manually.
(closes #110)
> tests: pytest manual run fix

- {{ cookiecutter.project_shortname }}/pytest.ini
- {{ cookiecutter.project_shortname }}/run-tests.sh
> tests: definition of testpaths

- .travis.yml
- run-tests.sh
- {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/views.py
> tests: travis script to run-tests.sh 

- {{ cookiecutter.project_shortname }}/CONTRIBUTING.rst
- {{ cookiecutter.project_shortname }}/docs/conf.py
> Updates from Sprint week 47-48

- {{ cookiecutter.project_shortname }}/.travis.yml
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
> templates: add allow_failures to .travis.yml

- {{ cookiecutter.project_shortname }}/run-tests.sh
Integrate changes from Invenio-Records.
- Ensure ``docker-services-cli down`` is being called on test failures
- Ensure fast failures when running tests.
- Add usage notes.
Pending decision on what to do with docker-services-cli and environment variables.
> tests: fix docker-services-cli issues

- .editorconfig
- .github/workflows/tests.yml
- README.rst
- scripts/repocheck.py
- {{ cookiecutter.project_shortname }}/.editorconfig
- {{ cookiecutter.project_shortname }}/.github/workflows/tests.yml
- {{ cookiecutter.project_shortname }}/CONTRIBUTING.rst
- {{ cookiecutter.project_shortname }}/run-tests.sh
* Removes references to TravisCI and `.travis.yml`.
* Closes #140.
PR created to keep track of the standard practices to implement GH actions workflows in Invenio.
> gh-actions: upgrade test workflow

- {{ cookiecutter.project_shortname }}/.gitignore
addresses this: https://github.com/inveniosoftware/invenio-vocabularies/pull/80#discussion_r681539283
> gitignore: ignore pipenv artefacts

- README.rst
- {{ cookiecutter.project_shortname }}/.github/workflows/i18n-pull.yml
- {{ cookiecutter.project_shortname }}/.github/workflows/i18n-push.yml
- {{ cookiecutter.project_shortname }}/.github/workflows/pypi-publish.yml
- {{ cookiecutter.project_shortname }}/.github/workflows/tests.yml
- {{ cookiecutter.project_shortname }}/.gitignore
- {{ cookiecutter.project_shortname }}/.tx/config
- {{ cookiecutter.project_shortname }}/CONTRIBUTING.rst
- {{ cookiecutter.project_shortname }}/misc/header.py
- {{ cookiecutter.project_shortname }}/setup.cfg
- {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/translations/messages.pot
:heart: Thank you for your contribution!
Addressing this comment: https://github.com/inveniosoftware/invenio-audit-logs/pull/1#discussion_r2003710930
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree …
> Update Outdated Settings
