inveniosoftware/cookiecutter-invenio-module

docs/index.rst, {{ cookiecutter.project_shortname }}/docs/index.rst
* Fixes relative path for `README.rst`. (addresses #9, closes #10)
=> docs: readme path fix

{{ cookiecutter.project_shortname }}/setup.py
=> installation: fix missing comma in classifiers

{{ cookiecutter.project_shortname }}/README.rst, {{ cookiecutter.project_shortname }}/RELEASE-NOTES.rst
* Uses more common "developer preview" phrase instead of "development
preview" phrase in the README and RELEASE-NOTES documentation
templates.
=> docs: development preview -> developer preview

cookiecutter.json, {{ cookiecutter.project_shortname }}/.tx/config, {{ cookiecutter.project_shortname }}/MANIFEST.in, {{ cookiecutter.project_shortname }}/examples/app.py, {{ cookiecutter.project_shortname }}/setup.py, {{ cookiecutter.project_shortname }}/tests/conftest.py, {{ cookiecutter.project_shortname }}/tests/test_{{cookiecutter.package_name}}.py, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/__init__.py, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/ext.py, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/templates/{{ cookiecutter.package_name }}/base.html, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/templates/{{ cookiecutter.package_name }}/index.html, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/views.py
* Adds boilerplate code and tests for Flask extension.
* Adds blueprint with support for templates and static folders.
* Adds dependency on Flask-BabelEx for gettext support.
* Adds support for uploading message catalogs to Transifex.
=> global: extension + i18n boiler plate

README.rst
* Fixes a typo in README.rst from Continues to Continuous.
=> docs: correction for typo Continues -> Continuous

{{ cookiecutter.project_shortname }}/docs/conf.py
* Changes the string format invocation in
{{cookiecutter-invenio-module/docs/conf.py.
(closes #39)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
=> docs: fix string format

{{ cookiecutter.project_shortname }}/.gitignore, {{ cookiecutter.project_shortname }}/MANIFEST.in
* Adds *.pot files to MANIFEST.in and removes them from .gitignore.
(related to inveniosoftware/invenio-accounts#46)
=> translations: inclusion of .pot files to MANIFEST

{{ cookiecutter.project_shortname }}/setup.cfg, {{ cookiecutter.project_shortname }}/setup.py
* Adds support for extracting notes to translators of a module.
=> installation: translation comments extraction

{{ cookiecutter.project_shortname }}/setup.py, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/ext.py, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/templates/{{ cookiecutter.package_name }}/index.html, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/views.py
* Adds extra todo items after bootstrapping. (closes #35)
* Adds entry points groups to setup.py. (addresses #31)
=> cookiecutter: todo additions and entry point fix

{{ cookiecutter.project_shortname }}/setup.cfg, {{ cookiecutter.project_shortname }}/setup.py
* BETTER Integrates pytest with setuptools by using pytest-runner.
=> cookiecutter: pytest-runner integration

{{ cookiecutter.project_shortname }}/CONTRIBUTING.rst
* FIX Removes a reference to Invenio and replaces it with a template
variable. (closes #26)
* FIX Replaces a link to travis-ci.com with a link to travis-ci.org.
=> docs: contribution guide updates

{{ cookiecutter.project_shortname }}/misc/header.jinja2, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/templates/{{ cookiecutter.package_name }}/base.html, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/templates/{{ cookiecutter.package_name }}/index.html
* FIX Adds missing licence headers for templates.  (closes #30)
=> global: addition of licence headers for templates

AUTHORS.rst
@helix84 FYI we use `kwalitee check authors` that expect git commit authors to be in AUTHORS.rst. Maybe we can relax the condition on diacritic ... cc @tiborsimko
=> docs: typo in author name fix

{{ cookiecutter.project_shortname }}/docs/conf.py
* Sets the autodoc configuration to insert into the main body of an
autoclass directive the documentation from the `__init__` method and
class documentation.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
=> docs: addition of autodoc configuration

README.rst
* Adds documentation for configuration options transifex_project,
extension_class and config_prefix.
Signed-off-by: David Caro <david@dcaro.es>
=> docs: transifex_project etc configuration options

{{ cookiecutter.project_shortname }}/examples/app.py, {{ cookiecutter.project_shortname }}/tests/test_example_app.py
This PR adds `test_example_app.py` to the package skeleton so that developers don't forget to write tests for example apps.
The current status of Invenio 3 package ecosystem as of 2016-08-31:
- the packages that have some example app tests:
- invenio-marc21
- invenio-records
- the packages that don't have any test for example app:
- domapping
- invenio-access
- invenio-accounts
- invenio-admin
- invenio-base
- invenio-circulation
- invenio-classifier
- invenio-collections
- invenio-communities
- invenio-csl-rest
- invenio-db/example/app.py
- invenio-deposit
- invenio-documents
- invenio-files-rest
- invenio-formatter
- invenio-github
- invenio-groups
- invenio-i18n
- invenio-indexer
- invenio-jsonschemas
- invenio-logging
- invenio-memento
- invenio-metrics
- invenio-oaiharvester
- …
=> tests: addition of test_example_app.py

.travis.yml, {{ cookiecutter.project_shortname }}/.travis.yml
* Adds `fast_finish` option to Travis CI templates so that Travis CI
builds would end as soon as one job fails. Helps to gain time.
=> RFC cookiecutter: fast_finish for Travis CI

.travis.yml, {{ cookiecutter.project_shortname }}/setup.py
* BETTER Removes a redundant Python versions for Travis.
Signed-off-by: PaulinaLach paulina.malgorzata.lach@cern.ch
=> travis: update tested Python versions

{{ cookiecutter.project_shortname }}/.travis.yml
travis' default nodejs is v0.10.36 which missing the ``isAbsolute`` attribute causing the ``clean-css`` to fail. 
Also the minimum requirement for ``clean-css`` is [v4](https://github.com/jakubpawlowicz/clean-css)
The best for us is to test on the latest LTS version which is for now ``v6.x``
```
Now using node v0.10.36 (npm v1.4.28)
➜ node
> require('path')
{ resolve: [Function],
normalize: [Function],
join: [Function],
relative: [Function],
sep: '/',
delimiter: ':',
dirname: [Function],
basename: [Function],
extname: [Function],
exists: [Function: deprecated],
existsSync: [Function: deprecated],
_makeLong: [Function] }
```
```
Now using node v6.9.5 (npm v3.10.10)
➜ node
> require('path')
{ resolve: [Function: resolve],
normalize: [Function: normalize],
isAbsolute: [Function: isAbsolute], …
```
=> travis: update nodejs to v6 LTS

{{ cookiecutter.project_shortname }}/docs/conf.py, {{ cookiecutter.project_shortname }}/pytest.ini, {{ cookiecutter.project_shortname }}/run-tests.sh
* Performs doctest execution within the initial pytest run, simplifying test
suite execution and solving "disappearing development requirements" problem
that was sometimes observed with development-level dependencies. (closes #97)
=> tests: doctext execution simplification

{{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/config.py, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/ext.py
* Updates ext.py so it uses variables from config.py
Signed-off-by: Rémi Ducceschi <remi.ducceschi@gmail.com>
This represents the new way of using config variables in modules. You can see examples here:
- https://github.com/inveniosoftware/invenio-access/blob/master/invenio_access/ext.py#L149
- https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/ext.py#L190
If you're OK with it, it may be useful that this PR gets merged before the IUGW2017.
=> config: use of variables from config.py in ext.py

{{ cookiecutter.project_shortname }}/tests/test_examples_app.py
- When used with vagrant, it is not enough to sleep 3 seconds.
At least 7 seconds are needed, otherwise the test won't pass
EITHER you merge this one, or https://github.com/inveniosoftware/invenio/pull/3784
=> tests: update sleep time

{{ cookiecutter.project_shortname }}/setup.cfg
* Ignores pydocstyle error code D401 ("First line should be in
imperative mood") as the parsing and detection is pretty broken.
(addresses inveniosoftware/troubleshooting#9)
=> tests: pydocstyle 2.0.0 imperative mood fix

cookiecutter.json
Fix bug if project name contains spaces.
=> cookiecutter: convert ' ' to '_' in config_prefix

{{ cookiecutter.project_shortname }}/.github/workflows/pypi-release.yml, {{ cookiecutter.project_shortname }}/.travis.yml, {{ cookiecutter.project_shortname }}/MANIFEST.in, {{ cookiecutter.project_shortname }}/pytest.ini, {{ cookiecutter.project_shortname }}/run-tests.sh, {{ cookiecutter.project_shortname }}/setup.cfg, {{ cookiecutter.project_shortname }}/setup.py
- Migrate to Pytest-Invenio centrally managed test dependencies
- Release packages using GH actions
**Questions**
@diegodelemos @lnielsen @inveniosoftware/architects 
This cookiecutter assumes no services are needed (e.g. it does not install `invenio-db`, `invenio-serach` or similar.) However, the `docker-services-cli` needs some input to boot up (e.g. `docker-services-cli up es mysql`). What should go to the `run-tests.sh` script?
- Specify nothing: up of *all* the services.
- Make cookiecutter aware of services: e.g. get user input for ES, DBs etc, and add them to `setup.py` and `run-tests.sh`.
Closes https://github.com/inveniosoftware/invenio/issues/4036
=> modifications from sharpen the saw sprint

{{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/ext.py, {{ cookiecutter.project_shortname }}/{{ cookiecutter.package_name }}/views.py
[Issue 150](https://github.com/inveniosoftware/cookiecutter-invenio-module/issues/150) describes deprecated imports of flask_babelex in the cookiecutter template. This pull request replaces them with the currently supported flask_babel.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.
=> Replaced deprecated flask_babelex with flask_babel
